export const presidents = [
    {
        name: "Dr. Rajendra Prasad",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/2/23/Dr._Rajendra_Prasad_Portrait.jpg",
        electionYear: "1952 (also 1957)",
        termStart: "26 Jan 1950",
        termEnd: "13 May 1962",
        vicePresidentBefore: "N/A",
        biography: "The first President of independent India and a major leader in the Indian independence movement. He played a prominent role in the Constituent Assembly.",
        constitutionalPowers: ["Heavily shaped the role of the President under the newly adopted Constitution."],
        importantDecisions: ["Promulgated the Hindu Code Bill.", "Pardoned various death sentences setting a precedent for presidential pardon."],
        facts: ["The only President to serve two full terms.", "Was a scholar and a lawyer by profession."]
    },
    {
        name: "Dr. Sarvepalli Radhakrishnan",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Dr_S_Radhakrishnan.jpg",
        electionYear: "1962",
        termStart: "13 May 1962",
        termEnd: "13 May 1967",
        vicePresidentBefore: "Yes (1st Vice President of India)",
        biography: "A prominent Indian philosopher and statesman. He was the first Vice President of India before being elected as the second President.",
        constitutionalPowers: ["Managed national crises during the Sino-Indian War and Indo-Pakistani War."],
        importantDecisions: ["Declared National Emergency during the wars of 1962 and 1965."],
        facts: ["His birthday (5 September) is celebrated in India as Teachers' Day.", "Awarded the Bharat Ratna in 1954."]
    },
    {
        name: "Dr. Zakir Husain",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/3/36/Zakir_Husain.jpg",
        electionYear: "1967",
        termStart: "13 May 1967",
        termEnd: "3 May 1969",
        vicePresidentBefore: "Yes",
        biography: "An eminent educationist and intellectual, Dr. Husain was a co-founder of Jamia Millia Islamia.",
        constitutionalPowers: ["Emphasized education as a means of national integration."],
        importantDecisions: ["Focus on educational reforms at the university level."],
        facts: ["First Muslim President of India.", "First President to die in office."]
    },
    {
        name: "V. V. Giri",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/8/87/V._V._Giri.jpg",
        electionYear: "1969",
        termStart: "24 Aug 1969",
        termEnd: "24 Aug 1974",
        vicePresidentBefore: "Yes",
        biography: "A prominent trade union leader and politician who served as acting President before being officially elected.",
        constitutionalPowers: ["Assented to the bank nationalization bill."],
        importantDecisions: ["Signed the historic ordinance nationalizing 14 major commercial banks."],
        facts: ["Only person to have served as both an acting President and President of India.", "Elected as an independent candidate."]
    },
    {
        name: "Fakhruddin Ali Ahmed",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/2/29/Fakhruddin_Ali_Ahmed.jpg",
        electionYear: "1974",
        termStart: "24 Aug 1974",
        termEnd: "11 Feb 1977",
        vicePresidentBefore: "No",
        biography: "A seasoned politician who served as a cabinet minister before becoming President.",
        constitutionalPowers: ["Issued the proclamation of Emergency in 1975 under Article 352."],
        importantDecisions: ["Signed the controversial declaration of the Emergency in 1975.", "Gave assent to multiple constitutional amendments."],
        facts: ["Second President to die in office.", "Had a deep interest in sports, particularly golf and tennis."]
    },
    {
        name: "Neelam Sanjiva Reddy",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Neelam_Sanjiva_Reddy.jpg",
        electionYear: "1977",
        termStart: "25 Jul 1977",
        termEnd: "25 Jul 1982",
        vicePresidentBefore: "No",
        biography: "A veteran political leader who served as the Chief Minister of Andhra Pradesh and Speaker of the Lok Sabha.",
        constitutionalPowers: ["Appointed multiple Prime Ministers during a politically volatile period."],
        importantDecisions: ["Dissolved the Lok Sabha in 1979 after Charan Singh's government collapsed."],
        facts: ["Youngest person to become President at that time.", "Elected unopposed as President."]
    },
    {
        name: "Giani Zail Singh",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Giani_Zail_Singh.jpg",
        electionYear: "1982",
        termStart: "25 Jul 1982",
        termEnd: "25 Jul 1987",
        vicePresidentBefore: "No",
        biography: "A seasoned politician from Punjab who had served as the Chief Minister of the state and as Union Home Minister.",
        constitutionalPowers: ["Used a pocket veto to block the Indian Post Office (Amendment) Bill."],
        importantDecisions: ["Presided over the volatile period of Operation Blue Star and the assassination of Indira Gandhi."],
        facts: ["First Sikh President of India.", "Known for his tense relationship with Prime Minister Rajiv Gandhi over certain policies."]
    },
    {
        name: "R. Venkataraman",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/7/75/Ramaswamy_Venkataraman.jpg",
        electionYear: "1987",
        termStart: "25 Jul 1987",
        termEnd: "25 Jul 1992",
        vicePresidentBefore: "Yes",
        biography: "A lawyer, freedom fighter, and politician who served as Vice President before assuming the highest office.",
        constitutionalPowers: ["Navigated India through a period of coalition politics, appointing four Prime Ministers."],
        importantDecisions: ["Ensured the stability of the parliamentary system amid frequent government changes."],
        facts: ["Served in the Indian freedom struggle and was jailed during the Quit India Movement.", "Oversaw the transition to economic liberalization in 1991."]
    },
    {
        name: "Dr. Shankar Dayal Sharma",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/a/af/Shankar_Dayal_Sharma.jpg",
        electionYear: "1992",
        termStart: "25 Jul 1992",
        termEnd: "25 Jul 1997",
        vicePresidentBefore: "Yes",
        biography: "A distinguished academician, lawyer, and former Vice President who led during a politically complex decade.",
        constitutionalPowers: ["Appointed three Prime Ministers during his tenure."],
        importantDecisions: ["Managed the aftermath of the Babri Masjid demolition (1992)."],
        facts: ["Served as the Chief Minister of Bhopal state before its merger.", "Known for his erudition and calm demeanor in crisis."]
    },
    {
        name: "K. R. Narayanan",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/8/87/K_R_Narayanan.jpg",
        electionYear: "1997",
        termStart: "25 Jul 1997",
        termEnd: "25 Jul 2002",
        vicePresidentBefore: "Yes",
        biography: "A former diplomat and the first President from the Dalit community, known for his strong independent views.",
        constitutionalPowers: ["Returned the cabinet recommendation to impose President's rule in UP and Bihar for reconsideration."],
        importantDecisions: ["Set the precedent of requiring letters of support from coalition partners before appointing a PM.", "First President to vote when in office (1998 general elections)."],
        facts: ["Described himself as a 'working President' rather than an 'executive' or 'rubber stamp' President.", "Served as Ambassador to the US, China, and the UK."]
    },
    {
        name: "Dr. A. P. J. Abdul Kalam",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/b/b0/A._P._J._Abdul_Kalam.jpg",
        electionYear: "2002",
        termStart: "25 Jul 2002",
        termEnd: "25 Jul 2007",
        vicePresidentBefore: "No",
        biography: "An aerospace scientist who played a pivotal role in India's civilian space program and military missile development.",
        constitutionalPowers: ["Returned the Office of Profit Bill for reconsideration (2006)."],
        importantDecisions: ["Supported India's nuclear weapons program while strongly advocating for youth education and technological advancement."],
        facts: ["Affectionately known as the 'People's President' and the 'Missile Man of India'.", "Only bachelor and first scientist to occupy Rashtrapati Bhavan."]
    },
    {
        name: "Pratibha Patil",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/6/67/Pratibha_Patil.jpg",
        electionYear: "2007",
        termStart: "25 Jul 2007",
        termEnd: "25 Jul 2012",
        vicePresidentBefore: "No",
        biography: "A lawyer and politician who previously served as the Governor of Rajasthan.",
        constitutionalPowers: ["Commuted a record number of death sentences to life imprisonment."],
        importantDecisions: ["Focused on women's empowerment and rural development issues during her speeches and tours."],
        facts: ["First female President of India.", "Flew in a Sukhoi Su-30MKI fighter jet during her tenure."]
    },
    {
        name: "Pranab Mukherjee",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Pranab_Mukherjee.jpg",
        electionYear: "2012",
        termStart: "25 Jul 2012",
        termEnd: "25 Jul 2017",
        vicePresidentBefore: "No",
        biography: "A veteran statesman who held numerous key cabinet portfolios (Finance, Defence, External Affairs) before his presidency.",
        constitutionalPowers: ["Rejected numerous mercy petitions, clearing a long backlog.", "Promulgated several key ordinances including the Criminal Law (Amendment) Ordinance, 2013."],
        importantDecisions: ["Oversaw the transition of power to a majority government in 2014 after decades of coalitions."],
        facts: ["Often referred to as the 'best Prime Minister India never had' due to his vast experience.", "Awarded the Bharat Ratna in 2019."]
    },
    {
        name: "Ram Nath Kovind",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Ram_Nath_Kovind_Official_Portrait.jpg",
        electionYear: "2017",
        termStart: "25 Jul 2017",
        termEnd: "25 Jul 2022",
        vicePresidentBefore: "No",
        biography: "A lawyer and politician who served as the Governor of Bihar prior to his presidency.",
        constitutionalPowers: ["Gave assent to landmark legislations including the abrogation of Article 370 and the Citizenship Amendment Act."],
        importantDecisions: ["Signed the Jammu and Kashmir Reorganisation Act, 2019.", "Oversaw the national response coordination during the COVID-19 pandemic."],
        facts: ["Second President from the Dalit community.", "Represented India extensively at the UN during his diplomatic career."]
    },
    {
        name: "Droupadi Murmu",
        portrait: "https://upload.wikimedia.org/wikipedia/commons/8/87/Droupadi_Murmu_Official_Portrait.jpg",
        electionYear: "2022",
        termStart: "25 Jul 2022",
        termEnd: "Present",
        vicePresidentBefore: "No",
        biography: "A teacher and politician who previously served as the Governor of Jharkhand.",
        constitutionalPowers: ["Continues to fulfill constitutional duties, providing assent to central bills and making key appointments."],
        importantDecisions: ["Focuses heavily on tribal rights, education, and women's empowerment in her official duties and speeches."],
        facts: ["First President from a tribal community.", "Youngest person to become President of India and the first born after independence."]
    }
];
